network:
  input_dim: 784
  num_workers: 4
  channels_img: 3  #1 for mnist, 3 for rgb
  z_dim: 20 # Compression level
  h_dim: 200 # Computational overhead


dataset:
  #dataset: "/media/danilo/hdd_0/Generative_Projects/DATASETs/CelebHQ/archive/celeba_hq"
  dataset: "MNIST"

training:
    lr: 3e-4  # Karpathy constant
    num_epochs: 10
    batch_sizes: 32
    optimizer: Adam #RMSprop #Adam
    #betas: [ 0.0, 0.99 ]